# Generated by Django 4.0.1 on 2022-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('entry', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='files/question_img')),
            ],
        ),
    ]
