# Generated by Django 4.0.1 on 2022-10-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
