# Generated by Django 4.0.1 on 2022-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='entry',
            field=models.TextField(max_length=1500),
        ),
    ]
