# Generated by Django 4.0.1 on 2022-11-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0005_alter_question_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum2.question'),
        ),
    ]
