# Generated by Django 4.0.1 on 2022-11-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0007_rename_author_comments_user_alter_comments_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='User',
        ),
    ]
