# Generated by Django 4.0.1 on 2022-11-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0008_rename_user_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='User',
            new_name='user',
        ),
    ]
