# Generated by Django 4.0.1 on 2022-11-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0009_rename_user_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum2.question'),
        ),
    ]
