# Generated by Django 4.0.1 on 2022-12-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum2', '0013_alter_comments_question_alter_comments_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
